# Generated by Django 5.1.2 on 2024-11-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "title",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("deletable", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "To Do Category",
                "verbose_name_plural": "To Do Categories",
            },
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("should_be_completed_by_date", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        default="N/A",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="todo.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "To Do",
                "verbose_name_plural": "To Do",
            },
        ),
    ]
