# Generated by Django 5.1.3 on 2024-11-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="should_be_completed_by_date",
            field=models.DateField(null=True),
        ),
    ]
