# Generated by Django 5.1.2 on 2024-11-01 05:24

from django.db import migrations


def add_initial_data(apps, schema_editor):
    MyModel = apps.get_model('todo', 'Category')
    initial_data = [
        MyModel(title="N/A", deletable=False),
        MyModel(title="Home", deletable=True),
        MyModel(title="Work", deletable=True),
    ]
    MyModel.objects.bulk_create(initial_data)



class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]



