# Generated by Django 5.1.3 on 2024-11-26 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todo_should_be_completed_by_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="should_be_completed_by_date",
        ),
    ]
