# Generated by Django 5.1.2 on 2024-11-01 05:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_add_initial_category_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "title",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("deletable", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "To Do Category",
                "verbose_name_plural": "To Do Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "To Do", "verbose_name_plural": "To Do"},
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="completed",
            new_name="is_completed",
        ),
        migrations.AddField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todo",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="should_be_completed_by_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.ForeignKey(
                default="N/A",
                on_delete=django.db.models.deletion.PROTECT,
                to="todo.category",
            ),
        ),
    ]
