# Generated by Django 5.1.3 on 2024-11-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_remove_todo_should_be_completed_by_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="should_be_completed_by_date",
            field=models.DateField(null=True),
        ),
    ]
