# Generated by Django 5.1.3 on 2024-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_todo_should_be_completed_by_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="should_be_completed_by_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
