# Generated by Django 5.1.5 on 2025-01-24 06:41

from django.db import migrations

def add_initial_todo_categories_data(apps, schema_editor):
    # Get the model
    ToDoCategory = apps.get_model('todo', 'Category')

    # Create initial data
    if not ToDoCategory.objects.filter(title='Family').exists():
        ToDoCategory.objects.create(title='Family')
    if not ToDoCategory.objects.filter(title='Home').exists():
        ToDoCategory.objects.create(title='Home')
    if not ToDoCategory.objects.filter(title='N/A').exists():
        ToDoCategory.objects.create(title='N/A', deletable=False)
    if not ToDoCategory.objects.filter(title='Work').exists():
        ToDoCategory.objects.create(title='Work')
        

def remove_initial_todo_categories_data(apps, schema_editor):
    # Get the model
    Category = apps.get_model('todo', 'Category')
    #
    Category.objects.filter(title='Family').delete()
    Category.objects.filter(title='Home').delete()
    Category.objects.filter(title='N/A').delete()
    Category.objects.filter(title='Work').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_todo_should_be_completed_by_date"),
    ]

    operations = [
        migrations.RunPython(add_initial_todo_categories_data, remove_initial_todo_categories_data),
    ]
